service: serverless-crud-jwt

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: create
          method: post
          cors: true
  read:
    handler: handler.read
    events:
      - http:
          path: read
          method: get
          cors: true
  update:
    handler: handler.update
    events:
      - http:
          path: update
          method: put
          cors: true
  delete:
    handler: handler.delete
    events:
      - http:
          path: delete
          method: delete
          cors: true

resources:
  Resources:
    MyDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.stage}-Table